name: Build and Deploy WASM

on:
  workflow_dispatch:  # Manuel tetikleme

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
    # 1. Kar deposunu checkout et
    - name: Checkout kar repository
      uses: actions/checkout@v2
      with:
        repository: setanarut/kar  # Kar deposunu checkout et
        path: kar

    # 2. Go'yu kur
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24.0'  # Kullanılan Go sürümü

    # 3. WASM dosyasını derle (cmd/kar/main.go dosyasını kullanarak)
    - name: Build WASM
      run: |
        cd kar/cmd/kar
        GOOS=js GOARCH=wasm go build -o kar.wasm main.go  # Derlenen dosya burada oluşturulacak

    # 4. GitHub Pages deposunu checkout et (main dalı)
    - name: Checkout setanarut.github.io repository
      uses: actions/checkout@v2
      with:
        repository: setanarut/setanarut.github.io
        path: setanarut.github.io
        token: ${{ secrets.GH_PAT }}  # PAT kullanarak yetki al
        ref: main  # Hedef dal "main" olduğundan emin ol

    # 6. WASM dosyasını kopyala
    - name: Copy WASM file to setanarut.github.io
      run: |
        cp kar/cmd/kar/kar.wasm setanarut.github.io/docs/kar/kar.wasm  # WASM dosyasını kopyala

    # 7. Değişiklikleri commit edip pushla (PAT ile Yetkilendirme)
    - name: Commit and Push to setanarut.github.io
      run: |
        cd setanarut.github.io
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/kar/kar.wasm
        git commit -m "Automated deployment: Update WASM file" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/setanarut/setanarut.github.io.git main
